# Generated by Django 2.0.1 on 2018-04-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180426_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='timeStamp',
            new_name='date',
        ),
    ]
