# Generated by Django 2.0.1 on 2018-04-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('fathersName', models.TextField()),
                ('mothersName', models.TextField()),
                ('pClass', models.IntegerField()),
                ('school', models.TextField()),
                ('address', models.TextField()),
                ('language', models.TextField()),
                ('contact', models.IntegerField()),
                ('registrationNo', models.TextField()),
                ('dataOfBirth', models.DateField()),
            ],
        ),
    ]
